spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_JWT_Token
    username: root
    password: admin1234
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mybatis.mapper/*.xml